
export enum TaskActionType {
  SET_FILTER = "SET_FILTER",
  
  ADD_TASK = "ADD_TASK",
  
  TOGGLE_COMPLETE = "TOGGLE_COMPLETE",
  
  REMOVE_TASK = "REMOVE_TASK",
  
  REMOVE_ALL_TASKS = "REMOVE_ALL_TASKS",
  
  EDIT_TASK_NAME = "EDIT_TASK_NAME",
}
